import type { Metadata } from "next";
import Link from "next/link";
import { PageIntro } from "@/components/page-intro";

export const metadata:Metadata={title:"Services",description:"Product engineering engagements designed around launch, scale, performance, AI readiness, and production recovery.",alternates:{canonical:"/services"}};
const situations=[
  {number:"01",title:"You need to launch a credible product or business website.",for:"Founders and companies that need one accountable path from requirement to production.",deliver:["Product discovery and scope","Design system and responsive build","SEO and analytics preparation","Production deployment and rollback"],proof:"PeterhofApart · ELVN"},
  {number:"02",title:"Your catalog or platform is becoming slow and expensive.",for:"Industrial suppliers and B2B teams with complex product data or an overloaded runtime.",deliver:["Runtime and crawl audit","Data-flow redesign","Precomputed artifacts and caching","Memory, response, and release validation"],proof:"ChipFasteners · ICPROM"},
  {number:"03",title:"You need an MVP without immediate technical debt.",for:"Product teams that need to test the critical workflow without building a speculative platform.",deliver:["Scope control and product architecture","Critical workflow implementation","Production launch","Next-stage decision plan"],proof:"ARMSENS Academy · ELVN"},
  {number:"04",title:"You want AI capabilities without lock-in or unreliable demos.",for:"Teams that need a safe, provider-independent path toward an LLM-enabled product.",deliver:["Use-case and risk definition","Provider abstraction","Deterministic fallback and evaluation","Privacy and readiness plan"],proof:"ARMSENS Academy architecture"},
];
export default function ServicesPage(){return <><PageIntro eyebrow="Services" title="Start with the business situation. Then choose the engineering response."><p>Engagements are scoped around a useful outcome, not a fixed menu of technologies. Pricing follows the actual constraints and delivery risk.</p></PageIntro><section className="section shell service-list">{situations.map((item)=><article key={item.number}><span className="service-number">{item.number}</span><div><h2>{item.title}</h2><p>{item.for}</p></div><div><strong>Typical delivery</strong><ul>{item.deliver.map((line)=><li key={line}>{line}</li>)}</ul><small>Relevant proof: {item.proof}</small></div></article>)}</section><section className="section shell service-catalog"><p className="eyebrow">Available engagements</p><div>{["Product Engineering","High-Performance Business Websites","B2B Catalog and Procurement Platforms","SaaS and MVP Development","AI-Ready Product Architecture","Technical SEO and Search Architecture","Performance Engineering","Production Deployment and Recovery"].map((service)=><span key={service}>{service}</span>)}</div><Link className="button" href="/contact">Describe your project <span aria-hidden="true">↗</span></Link></section></>}
