import type { Metadata } from "next";
import { ProductCTA, ProductHero, ProductSchema } from "@/components/revenueos/product-shell";
export const metadata:Metadata={title:"RevenueOS Security and Deployment",description:"Security, privacy, audit, recovery, and deployment principles for industrial revenue operations implementations.",alternates:{canonical:"/revenueos/security"}};
const principles=[
  ["Least privilege","Scoped integration identities and customer-approved permissions; no shared administrative credential as an operating pattern."],
  ["Deterministic records","Commercial identity, stages, price, supplier evidence, approvals, and payment remain authoritative outside AI output."],
  ["Durable delivery","Idempotent writes, outboxes, bounded retries, dead-letter evidence, and reconciliation protect system handoffs."],
  ["Auditable change","Sensitive operations retain an actor, time, entity, reason, and reviewable history."],
  ["Data minimization","Raw visitor identifiers are not required for commercial attribution; collection follows the agreed purpose and retention policy."],
  ["Secret isolation","Credentials remain server-side, encrypted where applicable, excluded from browser bundles, and redacted from logs."],
  ["Backup and restore","Ownership, frequency, retention, encryption, restore testing, and recovery objectives are defined for each deployment."],
  ["Controlled release","Immutable release artifacts, health checks, smoke tests, retained rollback, and documented handover are implementation requirements."],
];
export default function SecurityPage(){return <><ProductHero eyebrow="Security and deployment" title="Commercial reliability requires a defined responsibility boundary." lede="Security claims are limited to implemented controls and the agreed deployment. Certifications are never implied; customer review and contract terms control the final posture."/><section className="section shell security-grid">{principles.map(([title,text],index)=><article key={title}><span>0{index+1}</span><h2>{title}</h2><p>{text}</p></article>)}</section><section className="section section-contrast"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Deployment models</p><h2>Choose who operates each layer.</h2></div><p>Infrastructure control alone does not define security. Patch ownership, backup, observability, incident response, access review, and upgrade authority must be explicit.</p></div><div className="deployment-grid"><article><h3>Managed private cloud</h3><p>ELVN Studio operates an isolated environment under contracted controls and support responsibilities.</p></article><article><h3>Customer private cloud</h3><p>The customer owns the cloud boundary; delivery follows agreed roles, access, monitoring, and handover.</p></article><article><h3>Self-hosted</h3><p>The customer operates infrastructure with an active license and maintenance agreement covering supported releases and security work.</p></article></div></div></section><section className="section shell content-grid"><aside><p className="eyebrow">Review boundary</p><h2>What discovery must decide</h2></aside><div className="prose"><p>Data classes and residency, authentication and SSO, network exposure, secrets, integration permissions, retention, deletion, audit access, backup, recovery objectives, vulnerability handling, support access, and incident communication.</p><p>This page states design principles, not a certification, warranty, or substitute for a customer security review.</p></div></section><ProductCTA/><ProductSchema path="/revenueos/security" name="RevenueOS Security and Deployment" description="Security, privacy, recovery, and deployment principles."/></>}
