import type { Metadata } from "next";
import Link from "next/link";
import { ProductCTA, ProductHero, ProductSchema } from "@/components/revenueos/product-shell";
import { manufacturerCapabilities, manufacturerControls, manufacturerFaq, manufacturerFlow, manufacturerIntelligence, manufacturerPricing, manufacturerPricingFactors } from "@/lib/manufacturer-intelligence";

export const metadata: Metadata = {
  title: "Manufacturer Intelligence for Industrial Catalogs",
  description: manufacturerIntelligence.description,
  alternates: { canonical: "/revenueos/manufacturer-intelligence" },
  openGraph: { title: `ELVN ${manufacturerIntelligence.name}`, description: manufacturerIntelligence.tagline, url: "/revenueos/manufacturer-intelligence", images: [{ url: "/revenueos/og.png", width: 1200, height: 630, alt: "ELVN Manufacturer Intelligence" }] },
  twitter: { card: "summary_large_image", title: `ELVN ${manufacturerIntelligence.name}`, description: manufacturerIntelligence.tagline, images: ["/revenueos/og.png"] },
};

export default function ManufacturerIntelligencePage() {
  return <>
    <ProductHero eyebrow={`Revenue Operations · Product Data Intelligence · ${manufacturerIntelligence.version}`} title={manufacturerIntelligence.tagline} lede={manufacturerIntelligence.description} actions={false} />
    <section className="shell manufacturer-actions"><div className="button-row"><Link className="button" href="/revenueos/implementation#assessment">Request a Manufacturer Data Assessment <span aria-hidden="true">↗</span></Link><a className="button-quiet" href="#connector-architecture">Explore the Architecture</a></div><p className="product-status"><span className="status-dot" /> {manufacturerIntelligence.status} · Selected engagements</p></section>

    <section className="section shell content-grid"><aside><p className="eyebrow">The product-data problem</p><h2>Catalog scale creates an evidence problem before it creates an AI problem.</h2></aside><div className="prose"><p>Industrial product data is spread across official product pages, datasheets, package drawings, lifecycle notices, and customer-owned systems. Similar names do not make orderable variants interchangeable.</p><p>The safest unit of work is a governed manufacturer connector applied to a bounded cohort, with exact manufacturer and MPN identity preserved for every candidate field.</p></div></section>

    <section className="product-flow" id="connector-architecture"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Connector architecture</p><h2>Move from isolated SKU search to governed manufacturer intelligence.</h2></div><p>One approved manufacturer policy can support a bounded product cohort while every field still resolves back to an exact product and its evidence.</p></div><ol>{manufacturerFlow.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span><strong>{item}</strong></li>)}</ol></div></section>

    <section className="section shell"><div className="section-heading"><div><p className="eyebrow">Product capabilities</p><h2>Scale enrichment without weakening technical identity.</h2></div><p>Manufacturer-level reuse improves research efficiency. Exact-MPN validation and field-level evidence keep the result defensible.</p></div><div className="security-grid">{manufacturerCapabilities.map(([title, text], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h2>{title}</h2><p>{text}</p></article>)}</div></section>

    <section className="section section-contrast"><div className="shell content-grid"><aside><p className="eyebrow">AI boundary</p><h2>AI assists. Evidence controls publication.</h2></aside><div className="prose"><p>The module can run with AI disabled. When a customer-approved model is enabled, its suggestions remain visibly separate from deterministic identity, official evidence, reviewer decisions, and publication state.</p><p>Models may help rank candidates, classify documents, interpret tables, normalize units, explain conflicts, or summarize a review queue. They may not invent specifications, infer compliance, merge variants, declare evidence verified, or publish fields.</p><p><Link className="text-link" href="/revenueos/ai">Review the wider RevenueOS AI controls <span aria-hidden="true">↗</span></Link></p></div></div></section>

    <section className="section shell"><div className="section-heading"><div><p className="eyebrow">Non-negotiable controls</p><h2>Fail closed at every authority boundary.</h2></div><p>Source rights, identity, tenant ownership, review, and runtime safety are part of the product contract.</p></div><ol className="control-list">{manufacturerControls.map((control, index) => <li key={control}><span>{String(index + 1).padStart(2, "0")}</span>{control}</li>)}</ol></section>

    <section className="section product-evidence"><div className="shell content-grid"><aside><p className="eyebrow">Evidence passports</p><h2>Every proposed fact explains itself.</h2></aside><div className="prose"><p>A product field retains its tenant, manufacturer, exact MPN, raw and normalized value, qualifier, approved source reference, document location, connector version, extraction method, confidence, conflict state, reviewer state, publication state, and revalidation date.</p><p>This makes missing evidence visible and lets teams roll back a field without replacing the catalog or deleting its history. Customer source locations, access methods, credentials, and connector internals remain private.</p><p><Link className="text-link" href="/revenueos/knowledge-graph">See how commercial evidence connects in the Knowledge Graph <span aria-hidden="true">↗</span></Link></p></div></div></section>

    <section className="section shell content-grid"><aside><p className="eyebrow">Review and publication</p><h2>Research output is not production data.</h2></aside><div className="prose"><p>Candidate facts enter a review queue with their evidence and conflicts visible. Approved changes are assembled into an explicit publication batch that can be simulated, audited, and reversed.</p><p>Connectors and models cannot write directly into the public catalog. Ownership stays with the customer&apos;s existing catalog, PIM, ERP, or commerce system.</p></div></section>

    <section className="section section-contrast"><div className="shell content-grid"><aside><p className="eyebrow">Operating experience</p><h2>Designed around real industrial catalog constraints.</h2></aside><div className="prose"><p>The preview is informed by ELVN Studio&apos;s work with B2B product catalogs where technical identity, evidence quality, search behavior, and commercial workflows meet.</p><p><Link className="text-link" href="/work/icprom">View ICPROM work <span aria-hidden="true">↗</span></Link></p><p><Link className="text-link" href="/work/chipfasteners">View ChipFasteners work <span aria-hidden="true">↗</span></Link></p><p>Customer data, source locations, catalog counts, connector internals, and operational results are intentionally excluded from this public preview.</p></div></div></section>

    <section className="section shell content-grid"><aside><p className="eyebrow">Integration options</p><h2>Introduce the module beside the systems of record.</h2></aside><div className="prose"><p>Delivery may use versioned APIs, controlled files, durable queues, or customer-specific adapters after permissions, ownership, retries, and reconciliation are defined.</p><p><Link className="text-link" href="/revenueos/integrations">Review integration boundaries <span aria-hidden="true">↗</span></Link></p><p><Link className="text-link" href="/revenueos/implementation">Review the implementation program <span aria-hidden="true">↗</span></Link></p></div></section>

    <section className="section shell"><div className="section-heading"><div><p className="eyebrow">Typical engagements</p><h2>Start with source feasibility, not unlimited enrichment.</h2></div><p>Ranges are one-time assessment or implementation fees. Hosting, connector maintenance, refresh frequency, AI usage, review users, and support are scoped separately.</p></div><div className="pricing-preview">{manufacturerPricing.map(([name, range, summary]) => <article key={name}><h3>{name}</h3><strong>{range}</strong><span>Typical range</span><p>{summary}</p></article>)}</div><div className="manufacturer-price-factors"><h3>What changes the scope</h3><ul>{manufacturerPricingFactors.map((factor) => <li key={factor}>{factor}</li>)}</ul><p>Unlimited enrichment is not offered: source rights, exact identity, review capacity, refresh obligations, and publication risk must remain measurable.</p></div></section>

    <section className="section shell faq-list"><div className="section-heading"><div><p className="eyebrow">FAQ</p><h2>Clear boundaries before implementation.</h2></div></div>{manufacturerFaq.map(([question, answer], index) => <details key={question} open={index === 0}><summary><span>{String(index + 1).padStart(2, "0")}</span>{question}</summary><p>{answer}</p></details>)}</section>
    <ProductCTA title="Assess manufacturer coverage, identity risk, and source feasibility." />
    <ProductSchema path="/revenueos/manufacturer-intelligence" name="ELVN Manufacturer Intelligence" description={manufacturerIntelligence.description} faq={manufacturerFaq} />
  </>;
}
