import type { Metadata } from "next";
import { PageIntro } from "@/components/page-intro";
import { site } from "@/lib/site";

export const metadata: Metadata = { title: "Privacy", description: "How ELVN Studio handles contact details, server logs, analytics consent, and external links.", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() {
  return <><PageIntro eyebrow="Privacy" title="Only the data needed to answer and operate the site."><p>This page explains the public contact flow, necessary server logs, optional analytics, and your choices.</p></PageIntro><section className="section shell content-grid"><aside className="content-aside"><p>Controller contact</p><a className="text-link" href={`mailto:${site.email}`}>{site.email}</a></aside><div className="prose"><h2>Contact form</h2><p>When you submit an inquiry, the form processes the details you provide so ELVN Studio can understand and answer the request. Submissions are not stored in a website database. Delivery can use email and, when separately configured, a private Telegram notification.</p><h2>Abuse prevention and logs</h2><p>Necessary security controls process a request identifier, coarse request timing, and limited network information. Logs are minimized and used to detect errors or abuse, not to build advertising profiles.</p><h2>Analytics choice</h2><p>Google Analytics and Microsoft Clarity remain disabled until you select “Accept analytics.” If accepted, they measure site usage and interaction patterns so ELVN Studio can improve the experience. You can reject analytics without losing site functionality and clear the site’s local consent value at any time.</p><h2>External links</h2><p>Links to project websites, GitHub, X, Telegram, and email open services with their own privacy terms. ELVN Studio does not control their processing.</p><h2>Retention and rights</h2><p>Inquiry details are retained only as long as needed for the conversation, legal obligations, and reasonable security records. You may request access, correction, or deletion by emailing {site.email}.</p></div></section></>;
}
