export const site = {
  name: "ELVN Studio",
  shortName: "ELVN",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://studio.elvn.monster",
  description:
    "Independent product engineering studio for high-performance websites, B2B platforms, SaaS products, technical SEO, and production delivery.",
  email: "elvnask@gmail.com",
  social: {
    github: "https://github.com/elvn11ask",
    x: "https://x.com/elvn11ask",
    telegram: "https://t.me/elvnask",
  },
} as const;

export const primaryNavigation = [
  { href: "/revenueos", label: "Revenue Operations" },
  { href: "/work", label: "Work" },
  { href: "/services", label: "Services" },
  { href: "/process", label: "Process" },
  { href: "/about", label: "About" },
] as const;

export const staticRoutes = [
  "",
  "/work",
  "/services",
  "/process",
  "/skills",
  "/about",
  "/resume",
  "/contact",
  "/privacy",
  "/search",
  "/revenueos",
  "/revenueos/catalog-guard",
  "/revenueos/validation",
  "/revenueos/modules",
  "/revenueos/integrations",
  "/revenueos/ai",
  "/revenueos/pricing",
  "/revenueos/implementation",
  "/revenueos/security",
  "/revenueos/industrial-distribution",
  "/revenueos/electronic-components",
  "/revenueos/case-studies",
  "/revenueos/faq",
  "/revenueos/knowledge-graph",
  "/revenueos/knowledge-graph/architecture",
  "/revenueos/knowledge-graph/use-cases",
  "/revenueos/knowledge-graph/ai",
  "/revenueos/knowledge-graph/security",
  "/revenueos/knowledge-graph/pricing",
  "/revenueos/knowledge-graph/faq",
  "/revenueos/manufacturer-intelligence",
  "/news",
  "/news/revenue-knowledge-graph",
  "/news/manufacturer-intelligence",
] as const;
