import type { Metadata } from "next";
import Link from "next/link";
import { ProductCTA, ProductHero, ProductSchema } from "@/components/revenueos/product-shell";
import { aiCapabilities, implementationSteps, integrations, lifecycle, modules, pricing, revenueOS } from "@/lib/revenueos";

export const metadata: Metadata = {
  title: "Revenue Intelligence for Complex B2B Catalogs",
  description: "Find where catalog data, product visibility, and technical representation are preventing industrial products from being discovered and sold.",
  alternates: { canonical: "/revenueos" },
  openGraph: { title: "ELVN Revenue Operations", description: revenueOS.tagline, url: "/revenueos", images: [{ url: "/revenueos/og.png", width: 1200, height: 630, alt: "ELVN Revenue Operations — from RFQ to paid revenue" }] },
  twitter: { card: "summary_large_image", title: "ELVN Revenue Operations", description: revenueOS.tagline, images: ["/revenueos/og.png"] },
};

export default function RevenueOSPage() {
  const integrationGroups = [...new Set(integrations.map((item) => item.group))];
  return <>
    <ProductHero eyebrow="Revenue intelligence for complex B2B catalogs" title="Find where your catalog is losing visibility." lede="Revenue OS checks whether the products you sell can actually be found, indexed, and understood online—then gives catalog, web, and SEO teams an evidence-backed fix queue." />

    <section className="section shell studio-product-feature"><div><p className="eyebrow">Working commercial module</p><h2>Catalog Guard</h2><p>Run bounded, read-only checks across public product pages. Detect HTTP, sitemap, indexability, canonical, title, H1, Product schema, and response-time risks without submitting forms or changing production.</p></div><div className="studio-product-flow"><span>Catalog</span><span>Sitemap</span><span>Product page</span><span>Evidence</span><span>Severity</span><strong>Fix queue</strong></div><div className="button-row"><Link className="button" href="/revenueos/catalog-guard">Run Revenue Audit <span aria-hidden="true">↗</span></Link><Link className="button-quiet" href="/revenueos/validation">See measured validation</Link></div></section>

    <section className="product-flow" aria-labelledby="flow-title"><div className="shell"><div className="section-heading"><div><p className="eyebrow">RFQ to revenue</p><h2 id="flow-title">One commercial identity across the entire lifecycle.</h2></div><p>Each handoff produces an auditable event. Delivery, ownership, supplier cost, quote revisions, and payment no longer disappear between systems.</p></div><ol>{lifecycle.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span><strong>{item}</strong></li>)}</ol></div></section>

    <section className="section shell product-problem"><div><p className="eyebrow">The operating problem</p><h2>A submitted form is not revenue.</h2></div><div className="product-problem-grid"><article><span>01</span><h3>Requests get separated from product context</h3><p>Exact MPNs, quantities, BOM lines, and source pages are copied between forms, inboxes, CRM records, and spreadsheets.</p></article><article><span>02</span><h3>Sourcing is invisible to the pipeline</h3><p>A generic deal stage cannot explain which suppliers answered, whether a cost is still valid, or what blocks the quote.</p></article><article><span>03</span><h3>Traffic stops at conversion</h3><p>Analytics may report a form submission while management still cannot connect that visit to a quote, paid invoice, or margin.</p></article></div></section>

    <section className="section section-contrast"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Modular architecture</p><h2>Deploy the missing operating layer—not an unnecessary replacement program.</h2></div><p>Start with RFQ reliability and ownership. Add sourcing, quotes, attribution, the Knowledge Graph, or AI only when the underlying event chain is dependable.</p></div><div className="module-preview">{modules.slice(0, 8).map((module, index) => <article key={module.name}><span>{String(index + 1).padStart(2, "0")}</span><h3>{module.name}</h3><p>{module.outcome}</p></article>)}</div><div className="section-action"><Link className="text-link" href="/revenueos/modules">Explore all 21 modules <span aria-hidden="true">↗</span></Link></div></div></section>

    <section className="section shell product-reliability"><div><p className="eyebrow">Operational reliability</p><h2>The failure path is part of the product.</h2><p>Form acceptance, mail delivery, CRM synchronization, owner assignment, SLA deadlines, retries, and dead-letter states are treated as explicit commercial evidence.</p></div><div className="event-ledger" aria-label="Example operational event ledger"><div><span>09:14:02</span><strong>RFQ accepted</strong><em>rfq_0142</em></div><div><span>09:14:03</span><strong>Mailbox confirmed</strong><em>delivery_8831</em></div><div><span>09:16:18</span><strong>Owner assigned</strong><em>sales_industrial</em></div><div><span>11:42:50</span><strong>Supplier response</strong><em>3 / 5 lines</em></div><div><span>15:08:11</span><strong>Quote revision 01</strong><em>margin reviewed</em></div></div></section>

    <section className="section product-attribution"><div className="shell split-section"><div><p className="eyebrow">Revenue attribution</p><h2>Know which product pages create paid margin—not only sessions.</h2></div><div className="attribution-chain"><span>Canonical PDP</span><span>Qualified RFQ</span><span>Quoted lines</span><span>Purchase order</span><span>Paid invoice</span><strong>Revenue + margin</strong></div></div></section>

    <section className="section shell studio-product-feature"><div><p className="eyebrow">New design partner module</p><h2>Revenue Knowledge Graph</h2><p>Connect product, RFQ, supplier, quote, payment, and margin evidence in a reproducible projection while each operational system remains authoritative.</p></div><div className="studio-product-flow"><span>Product</span><span>RFQ</span><span>Supplier</span><span>Quote</span><span>Payment</span><strong>Margin evidence</strong></div><div className="button-row"><Link className="button" href="/revenueos/knowledge-graph">Explore the Knowledge Graph <span aria-hidden="true">↗</span></Link><Link className="button-quiet" href="/news/revenue-knowledge-graph">Read the launch note</Link></div></section>

    <section className="section shell ai-preview"><div className="section-heading"><div><p className="eyebrow">Bring Your Own AI · Optional</p><h2>Assistance without surrendering commercial control.</h2></div><p>The deterministic system works without a model. AI can summarize, classify, draft, and flag risk, but it does not silently change product identity, price, supplier, or customer communication.</p></div><div className="capability-line">{aiCapabilities.slice(0, 10).map((item) => <span key={item}>{item}</span>)}</div><div className="section-action"><Link className="text-link" href="/revenueos/ai">Review AI controls and providers <span aria-hidden="true">↗</span></Link></div></section>

    <section className="section section-contrast"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Integration landscape</p><h2>Connect the systems you operate now.</h2></div><p>Native adapters are distinguished from API integrations, file bridges, webhooks, and work that still requires discovery. No connector is described as production-ready before validation.</p></div><div className="integration-groups">{integrationGroups.map((group) => <article key={group}><h3>{group}</h3><p>{integrations.filter((item) => item.group === group).slice(0, 7).map((item) => item.name).join(" · ")}</p></article>)}</div><div className="section-action"><Link className="text-link" href="/revenueos/integrations">See integration classifications <span aria-hidden="true">↗</span></Link></div></div></section>

    <section className="section shell"><div className="section-heading"><div><p className="eyebrow">Deployment choices</p><h2>Managed private cloud or customer-controlled infrastructure.</h2></div><p>The deployment boundary follows data policy, integrations, support responsibility, backup ownership, and security review—not a one-size-fits-all SaaS assumption.</p></div><div className="deployment-grid"><article><span>01</span><h3>Managed private cloud</h3><p>Isolated production environment with agreed monitoring, backup, upgrades, and support.</p></article><article><span>02</span><h3>Customer private cloud</h3><p>Deployment inside a customer-controlled cloud account with a documented responsibility split.</p></article><article><span>03</span><h3>Self-hosted</h3><p>Annual license, implementation, mandatory first-year support, and an active maintenance path for upgrades and security.</p></article></div><div className="section-action"><Link className="text-link" href="/revenueos/security">Security and deployment principles <span aria-hidden="true">↗</span></Link></div></section>

    <section className="section product-evidence"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Implementation evidence</p><h2>Developed from operating real B2B catalog and RFQ systems.</h2></div><p>Public claims stay deliberately narrow. RevenueOS components are locally validated; production integration and shadow reconciliation remain implementation gates.</p></div><div className="case-preview"><article><p className="eyebrow">Industrial catalog migration</p><h3>Preserving commercial routes while moving stable catalog work outside the hot request path.</h3><Link className="text-link" href="/revenueos/case-studies#industrial">Read the framework <span aria-hidden="true">↗</span></Link></article><article><p className="eyebrow">Electronic component procurement</p><h3>Connecting deterministic product identity, BOM intake, RFQ reliability, and commercial trust.</h3><Link className="text-link" href="/revenueos/case-studies#components">Read the framework <span aria-hidden="true">↗</span></Link></article></div></div></section>

    <section className="section shell"><div className="section-heading"><div><p className="eyebrow">Typical engagement ranges</p><h2>Enough pricing to qualify the project before discovery.</h2></div><p>The main ranges are one-time audit or implementation prices. Any monthly or annual platform and support charge is shown separately.</p></div><div className="pricing-preview">{pricing.slice(0, 4).map((item) => <article key={item.name}><h3>{item.name}</h3><strong>{item.range}</strong><span>{item.basis}</span><p>{item.recurring}</p></article>)}</div><div className="section-action"><Link className="text-link" href="/revenueos/pricing">Review all engagement ranges <span aria-hidden="true">↗</span></Link></div></section>

    <section className="section product-implementation"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Implementation</p><h2>Prove the event chain before expanding scope.</h2></div><p>A pilot runs beside the current workflow, reconciles source records, and earns the right to own more of the commercial process.</p></div><ol>{implementationSteps.slice(0, 4).map(([number, title, text]) => <li key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></div></section>
    <ProductCTA />
    <ProductSchema path="/revenueos" name="ELVN Revenue Operations" description={revenueOS.tagline} />
  </>;
}
