import type { Metadata } from "next";
import Link from "next/link";
import { ProductHero, ProductSchema } from "@/components/revenueos/product-shell";

export const metadata: Metadata = {
  title: "Revenue OS — Website & Catalog Intelligence",
  description: "Detect website regressions, work an evidence-backed issue queue, and verify fixes. Specialized catalog intelligence for complex product sites.",
  alternates: { canonical: "/revenueos" },
};

const checks = ["HTTP", "Redirects", "Indexability", "Canonical", "Titles", "Descriptions", "H1", "Structured data", "Internal links", "Latency"];

export default function RevenueOSPage() {
  return <>
    <ProductHero eyebrow="Website & catalog intelligence · Private beta" title="Find what changed before it costs visibility, leads, or sales." lede="Revenue OS continuously checks the public parts of a commercial website, groups regressions into a work queue, and verifies whether the fix actually worked." status={false} compact />

    <section className="section shell ros-workspace-section"><div className="section-heading"><div><p className="eyebrow">The product, not an AI demo</p><h2>One queue for what changed, what broke, and what to verify.</h2></div><p>The workspace stores observed pages, grouped issues, scan history, evidence, status changes and verification results. AI is not required.</p></div><div className="ros-workspace" role="img" aria-label="Revenue OS private-beta workspace overview"><aside><strong>Revenue OS</strong>{["Overview","Website","Catalog","Issues","Scans","Reports","Integrations","Team","Settings"].map((item) => <span className={item === "Overview" ? "active" : ""} key={item}>{item}</span>)}</aside><main><header><div><small>ICPROM workspace</small><h3>What needs attention today?</h3></div><b>PUBLIC_WEB · ZERO WRITES</b></header><div className="ros-metrics"><article><span>Pages tracked</span><strong>75</strong></article><article><span>Open issues</span><strong>75</strong></article><article><span>Critical</span><strong>0</strong></article><article><span>Regressions</span><strong>0</strong></article></div><section><div><small>MEDIUM · PUBLIC_WEB</small><h4>Product structured data is missing</h4><p>25 affected pages · measured fact · revenue impact unquantified</p></div><span>ACTION REQUIRED</span></section><section><div><small>SCAN HISTORY</small><h4>Bounded production validation</h4><p>25 pages · 0 request errors · 0 writes</p></div><span>COMPLETED</span></section></main></div><p className="ros-caption">Real private-beta information architecture. Validation figures shown are the measured 25-page ICPROM cohort, not a customer outcome.</p></section>

    <section className="section section-contrast"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Choose the problem</p><h2>One universal core. Three clear modules.</h2></div><p>Start without integrations or a catalog. Add specialized data only when it creates a better decision.</p></div><div className="ros-module-grid"><article><span>WORKING BETA</span><h3>Website Guard</h3><p>Bounded scans, page inventory, grouped issues, change history and fix verification for any authorized commercial website.</p><Link href="/revenueos/website-guard">See Website Guard →</Link></article><article><span>WORKING BETA</span><h3>Catalog Guard</h3><p>Deeper product-page and exact-identity analysis for distributors, manufacturers, e-commerce and marketplaces.</p><Link href="/revenueos/catalog-guard">See Catalog Guard →</Link></article><article><span>LIMITED PILOT</span><h3>Migration Guard</h3><p>Compare a baseline with staging or a new site and make a release decision from grouped regressions.</p><Link href="/revenueos/migration-guard">Review pilot scope →</Link></article></div></div></section>

    <section className="section shell"><div className="section-heading"><div><p className="eyebrow">Framework-independent by default</p><h2>The scanner reads web contracts, not CMS brand names.</h2></div><p>Server-rendered and static HTML are inspected directly. Client-rendered application shells are detected and labeled for the bounded browser-rendering adapter.</p></div><div className="ros-contracts">{checks.map((check) => <span key={check}>{check}</span>)}</div><div className="button-row ros-link-row"><Link className="button-quiet" href="/revenueos/platforms">Platform support and limitations</Link><Link className="text-link" href="/revenueos/security">Security boundary</Link></div></section>

    <section className="section product-evidence"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Measured engineering validation · 2026-08-28</p><h2>95 public pages. Five environments. Zero request errors.</h2></div><p>75 industrial product pages plus 20 pages across a Next.js site and a non-catalog commercial website. Sequential, bounded and read-only. This is engineering validation, not a customer result.</p></div><div className="ros-proof"><article><strong>95</strong><span>pages checked</span></article><article><strong>5</strong><span>environments</span></article><article><strong>0</strong><span>request errors</span></article><article><strong>0</strong><span>production writes</span></article></div><div className="section-action"><Link className="text-link" href="/revenueos/validation">Method, sample, findings and limitations →</Link></div></div></section>

    <section className="section shell content-grid"><aside><p className="eyebrow">First commercial motion</p><h2>Pay for an audit, not a promise.</h2></aside><div className="prose"><h2>Website Revenue Risk Audit</h2><p>For a commercial site without catalog data: bounded baseline, technical and visibility risks, grouped issue queue, private report and remediation plan. Pricing is scoped after page volume and authorization.</p><h2>Catalog Revenue Leak Audit · from $1,500</h2><p>For complex product sites: website baseline plus catalog import, exact identity review, catalog-to-site coverage and prioritized product visibility gaps. Revenue impact is never invented.</p><div className="button-row"><Link className="button" href="/contact?interest=revenue-audit">Request an audit <span aria-hidden="true">↗</span></Link><Link className="button-quiet" href="/revenueos/catalog-guard">Catalog audit scope</Link></div></div></section>

    <ProductSchema path="/revenueos" name="Revenue OS" description="Website and catalog intelligence with bounded scans, grouped issues, history and fix verification." />
  </>;
}
