import type { Metadata } from "next";
import Link from "next/link";
import { ProductCTA, ProductHero, ProductSchema } from "@/components/revenueos/product-shell";

export const metadata: Metadata = { title: "Website Guard — Website Regression Monitoring", description: "Bounded website scans, page inventory, grouped issues, change history and fix verification without catalog data.", alternates: { canonical: "/revenueos/website-guard" } };

const checks = [["Availability", "HTTP failures, unexpected redirects and disappeared important pages."], ["Visibility", "Robots, noindex, sitemap, canonical, titles, descriptions and headings."], ["Structure", "Schema types, internal links and recurring page classes."], ["Change", "New, removed and changed pages plus new, resolved and regressed issues."], ["Performance", "Network response timing with explicit methodology; not mislabeled as Core Web Vitals."], ["Rendering boundary", "Client-rendered shells are detected and queued for an optional bounded browser pass."]];

export default function WebsiteGuardPage() { return <><ProductHero eyebrow="Website Guard · Working private beta" title="Your website changes constantly. Know when something important breaks." lede="Connect an authorized public website without a catalog or integration. Revenue OS builds a bounded inventory, groups findings into operational issues and compares every successful scan with the previous one." actions={false} /><section className="section shell"><div className="module-preview">{checks.map(([title,text],i)=><article key={title}><span>{String(i+1).padStart(2,"0")}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="section section-contrast"><div className="shell content-grid"><aside><p className="eyebrow">Operational loop</p><h2>No fake buttons.</h2></aside><div className="prose"><h2>Connect → baseline → issue queue → status → re-scan → verify</h2><p>The private workspace stores the website, bounded scan job, page hashes and extracted facts, grouped issue occurrences, status history and private report. Scheduled daily or weekly jobs use the same worker queue and reject overlapping scans.</p><p>Current limitation: browser-rendered DOM, mobile and visual checks are not yet operational in the worker. The scanner labels pages that need that adapter instead of pretending the server HTML is complete.</p></div></div></section><section className="section shell"><div className="ros-proof"><article><strong>20</strong><span>non-catalog pages</span></article><article><strong>2</strong><span>site types</span></article><article><strong>0</strong><span>request errors</span></article><article><strong>0</strong><span>writes or forms</span></article></div><div className="section-action"><Link className="text-link" href="/revenueos/validation">Validation methodology →</Link></div></section><ProductCTA title="Start with one bounded website baseline."/><ProductSchema path="/revenueos/website-guard" name="Revenue OS Website Guard" description="Protocol-first website monitoring with grouped issues, history and fix verification."/></> }
